apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: javaee-cafe-mssql-auth-aad-password
  namespace: ${NAMESPACE}
spec:
  replicas: 3
  applicationImage: ${LOGIN_SERVER}/${IMAGE}:${TAG}
  pullPolicy: Always
  service:
    type: LoadBalancer
    port: 80
    targetPort: 9080
  env:
  - name: DB_SERVER_NAME
    valueFrom:
      secretKeyRef:
        name: db-secret-mssql
        key: db.server.name
  - name: DB_PORT_NUMBER
    valueFrom:
      secretKeyRef:
        name: db-secret-mssql
        key: db.port.number
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: db-secret-mssql
        key: db.name
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: db-secret-mssql
        key: db.user
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secret-mssql
        key: db.password
