FROM openjdk:11
ADD target/sql-auth-aad-password-1.0-SNAPSHOT-jar-with-dependencies.jar sql-auth-aad-password-1.0-SNAPSHOT-jar-with-dependencies.jar
ENTRYPOINT ["java", "-jar","sql-auth-aad-password-1.0-SNAPSHOT-jar-with-dependencies.jar"]
